ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module

jwt:
  secret: "$JWT_SECRET:**************************************"
  issuer: "fitness-app"
  audience: "fitness-app-users"
  expiry: 86400000

database:
  url: "$DB_URL:jdbc:postgresql://localhost:5432/fitnessdb"
  driver: "org.postgresql.Driver"
  user: "$DB_USER:postgres"
  password: "$DB_PASSWORD:postgres"
